In [1]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv('../data/GlobalWeatherRepository.csv')

In [7]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139553,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1777963500,2026-05-05 02:45,17.7,63.9,Clear,...,9.95,11.45,1,1,06:08 AM,06:40 PM,10:11 PM,08:57 AM,Waning Gibbous,89
139554,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1777963500,2026-05-05 13:45,30.1,86.2,Overcast,...,134.45,142.45,4,10,05:24 AM,06:23 PM,09:41 PM,07:36 AM,Waning Gibbous,92
139555,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1777963500,2026-05-05 09:45,23.0,73.3,Sunny,...,12.95,46.45,1,2,05:38 AM,06:22 PM,09:42 PM,08:05 AM,Waning Gibbous,91
139556,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1777963500,2026-05-05 08:45,19.9,67.8,Sunny,...,5.25,5.95,1,1,06:18 AM,05:49 PM,08:38 PM,09:21 AM,Waning Gibbous,91
139557,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1777963500,2026-05-05 08:45,18.0,64.5,Sunny,...,10.25,10.85,1,1,06:10 AM,05:35 PM,08:21 PM,09:16 AM,Waning Gibbous,91

In [8]:
alfa = df[['country', 'location_name', 'latitude', 'longitude', 'last_updated', 'temperature_celsius', 'condition_text', 'wind_kph', 'precip_mm', 'humidity', 'cloud', 'air_quality_gb-defra-index', 'sunrise', 'sunset']]

In [9]:
alfa['last_updated'] = pd.to_datetime(alfa['last_updated'])

C:\Users\Varushet\AppData\Local\Temp\ipykernel_6296\2942765334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alfa['last_updated'] = pd.to_datetime(alfa['last_updated'])

In [10]:
alfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139558 entries, 0 to 139557
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   country                     139558 non-null  object
 1   location_name               139558 non-null  object
 2   latitude                    139558 non-null  float64
 3   longitude                   139558 non-null  float64
 4   last_updated                139558 non-null  datetime64[ns]
 5   temperature_celsius         139558 non-null  float64
 6   condition_text              139558 non-null  object
 7   wind_kph                    139558 non-null  float64
 8   precip_mm                   139558 non-null  float64
 9   humidity                    139558 non-null  int64
 10  cloud                       139558 non-null  int64
 11  air_quality_gb-defra-index  139558 non-null  int64
 12  sunrise                     139558 non-null  object
 13  sunset                      139558 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(3), object(5)
memory usage: 14.9+ MB

In [11]:
alfa

,country,location_name,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_kph,precip_mm,humidity,cloud,air_quality_gb-defra-index,sunrise,sunset
0,Afghanistan,Kabul,34.5200,69.1800,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,0.0,24,30,1,04:50 AM,06:50 PM
1,Albania,Tirana,41.3300,19.8200,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,0.1,94,75,1,05:21 AM,07:54 PM
2,Algeria,Algiers,36.7600,3.0500,2024-05-16 09:45:00,23.0,Sunny,15.1,0.0,29,0,1,05:40 AM,07:50 PM
3,Andorra,Andorra La Vella,42.5000,1.5200,2024-05-16 10:45:00,6.3,Light drizzle,11.9,0.3,61,100,1,06:31 AM,09:11 PM
4,Angola,Luanda,-8.8400,13.2300,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,0.0,89,50,10,06:12 AM,05:55 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139553,Venezuela,Caracas,10.5000,-66.9167,2026-05-05 02:45:00,17.7,Clear,7.6,0.0,81,13,1,06:08 AM,06:40 PM
139554,Vietnam,Hanoi,21.0333,105.8500,2026-05-05 13:45:00,30.1,Overcast,9.4,0.0,55,25,10,05:24 AM,06:23 PM
139555,Yemen,Sanaa,15.3547,44.2067,2026-05-05 09:45:00,23.0,Sunny,9.7,0.0,27,2,2,05:38 AM,06:22 PM
139556,Zambia,Lusaka,-15.4167,28.2833,2026-05-05 08:45:00,19.9,Sunny,11.2,0.0,72,17,1,06:18 AM,05:49 PM
139557,Zimbabwe,Harare,-17.8178,31.0447,2026-05-05 08:45:00,18.0,Sunny,9.7,0.0,64,3,1,06:10 AM,05:35 PM

In [12]:
alfa['year'] = alfa['last_updated'].dt.year
alfa['month'] = alfa['last_updated'].dt.month
alfa['day'] = alfa['last_updated'].dt.day
alfa = alfa.drop(columns='last_updated')

C:\Users\Varushet\AppData\Local\Temp\ipykernel_6296\2281748589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alfa['year'] = alfa['last_updated'].dt.year
C:\Users\Varushet\AppData\Local\Temp\ipykernel_6296\2281748589.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alfa['month'] = alfa['last_updated'].dt.month
C:\Users\Varushet\AppData\Local\Temp\ipykernel_6296\2281748589.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alfa['day'] = alfa['last_updated'].dt.day

In [13]:
alfa['sr_dt'] = pd.to_datetime(alfa['sunrise'])
alfa['ss_dt'] = pd.to_datetime(alfa['sunset'])

C:\Users\Varushet\AppData\Local\Temp\ipykernel_6296\1434139465.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  alfa['sr_dt'] = pd.to_datetime(alfa['sunrise'])
C:\Users\Varushet\AppData\Local\Temp\ipykernel_6296\1434139465.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  alfa['ss_dt'] = pd.to_datetime(alfa['sunset'])

In [14]:
alfa['light_h'] = alfa['ss_dt'] - alfa['sr_dt']

In [15]:
alfa

,country,location_name,latitude,longitude,temperature_celsius,condition_text,wind_kph,precip_mm,humidity,cloud,air_quality_gb-defra-index,sunrise,sunset,year,month,day,sr_dt,ss_dt,light_h
0,Afghanistan,Kabul,34.5200,69.1800,26.6,Partly Cloudy,13.3,0.0,24,30,1,04:50 AM,06:50 PM,2024,5,16,2026-05-06 04:50:00,2026-05-06 18:50:00,0 days 14:00:00
1,Albania,Tirana,41.3300,19.8200,19.0,Partly cloudy,11.2,0.1,94,75,1,05:21 AM,07:54 PM,2024,5,16,2026-05-06 05:21:00,2026-05-06 19:54:00,0 days 14:33:00
2,Algeria,Algiers,36.7600,3.0500,23.0,Sunny,15.1,0.0,29,0,1,05:40 AM,07:50 PM,2024,5,16,2026-05-06 05:40:00,2026-05-06 19:50:00,0 days 14:10:00
3,Andorra,Andorra La Vella,42.5000,1.5200,6.3,Light drizzle,11.9,0.3,61,100,1,06:31 AM,09:11 PM,2024,5,16,2026-05-06 06:31:00,2026-05-06 21:11:00,0 days 14:40:00
4,Angola,Luanda,-8.8400,13.2300,26.0,Partly cloudy,13.0,0.0,89,50,10,06:12 AM,05:55 PM,2024,5,16,2026-05-06 06:12:00,2026-05-06 17:55:00,0 days 11:43:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139553,Venezuela,Caracas,10.5000,-66.9167,17.7,Clear,7.6,0.0,81,13,1,06:08 AM,06:40 PM,2026,5,5,2026-05-06 06:08:00,2026-05-06 18:40:00,0 days 12:32:00
139554,Vietnam,Hanoi,21.0333,105.8500,30.1,Overcast,9.4,0.0,55,25,10,05:24 AM,06:23 PM,2026,5,5,2026-05-06 05:24:00,2026-05-06 18:23:00,0 days 12:59:00
139555,Yemen,Sanaa,15.3547,44.2067,23.0,Sunny,9.7,0.0,27,2,2,05:38 AM,06:22 PM,2026,5,5,2026-05-06 05:38:00,2026-05-06 18:22:00,0 days 12:44:00
139556,Zambia,Lusaka,-15.4167,28.2833,19.9,Sunny,11.2,0.0,72,17,1,06:18 AM,05:49 PM,2026,5,5,2026-05-06 06:18:00,2026-05-06 17:49:00,0 days 11:31:00
139557,Zimbabwe,Harare,-17.8178,31.0447,18.0,Sunny,9.7,0.0,64,3,1,06:10 AM,05:35 PM,2026,5,5,2026-05-06 06:10:00,2026-05-06 17:35:00,0 days 11:25:00

In [16]:
# .dt.total_seconds() nos da los segundos, dividimos por 3600 para tener horas
alfa['sun_h'] = alfa['light_h'].dt.total_seconds() / 3600
alfa['sun_h'] = alfa['sun_h'].round(2)

In [17]:
alfa.drop(columns=['sr_dt', 'ss_dt', 'light_h', 'sunrise', 'sunset'], inplace=True)

In [18]:
alfa[['latitude', 'longitude']] = alfa[['latitude', 'longitude']].round(2)

In [19]:
alfa.rename(columns={'location_name': 'capital', 'temperature_celsius': 'temp_C', 'air_quality_gb-defra-index': 'Air_poll'}, inplace=True)

In [20]:
alfa['country_id'], uniques = pd.factorize(alfa['country'])

In [21]:
alfa = alfa[['year', 'month', 'day', 'country_id', 'country', 'capital', 'latitude', 'longitude', 'wind_kph', 'precip_mm', 'humidity', 'cloud', 'Air_poll', 'sun_h', 'temp_C']]
alfa

,year,month,day,country_id,country,capital,latitude,longitude,wind_kph,precip_mm,humidity,cloud,Air_poll,sun_h,temp_C
0,2024,5,16,0,Afghanistan,Kabul,34.52,69.18,13.3,0.0,24,30,1,14.00,26.6
1,2024,5,16,1,Albania,Tirana,41.33,19.82,11.2,0.1,94,75,1,14.55,19.0
2,2024,5,16,2,Algeria,Algiers,36.76,3.05,15.1,0.0,29,0,1,14.17,23.0
3,2024,5,16,3,Andorra,Andorra La Vella,42.50,1.52,11.9,0.3,61,100,1,14.67,6.3
4,2024,5,16,4,Angola,Luanda,-8.84,13.23,13.0,0.0,89,50,10,11.72,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139553,2026,5,5,180,Venezuela,Caracas,10.50,-66.92,7.6,0.0,81,13,1,12.53,17.7
139554,2026,5,5,181,Vietnam,Hanoi,21.03,105.85,9.4,0.0,55,25,10,12.98,30.1
139555,2026,5,5,182,Yemen,Sanaa,15.35,44.21,9.7,0.0,27,2,2,12.73,23.0
139556,2026,5,5,183,Zambia,Lusaka,-15.42,28.28,11.2,0.0,72,17,1,11.52,19.9
139557,2026,5,5,184,Zimbabwe,Harare,-17.82,31.04,9.7,0.0,64,3,1,11.42,18.0

In [2]:
df = pd.read_csv('../data/climaDS.csv.gz')

In [ ]:
counts = df['country_id'].value_counts()
valid_countries = counts[counts >= 5].index
df_clean = df[df['country_id'].isin(valid_countries)].copy()

In [4]:
df_clean['country_id'], uniques = pd.factorize(df_clean['country'])

In [10]:
df_clean.to_csv('../data/climaDS.csv.gz', index=False, compression='gzip')